spring:
  application:
    name: book-social-api

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1